### ISSUE TITLE
ForeachVsFor compares different things

### ISSUE THREAD

**Issue by IvanFeric** [marko-lohert/High-Performance-CSharp-Samples-With-Benchmarks#1]
Hi, I was looking at your repo and went through the samples to compare different approaches. I stumbled upon the code sample `ForeachVsFor.cs` and noticed that the `ForEach` method doesn't do the same thing as the `ForLoop` does.

To be more precise, `ForEach` is iterating over the array. Values in the array are always between 0 and 10. Then, based on the value we got, we're using it as an index to search for the value to sum. `ForLoop` sample doesn't use it as an index and sums it up directly.

However, I did run the benchmark locally and with the current code, on my machine, the `ForLoop` ratio was around 0.30.

With updated code (by replacing `sum += Data[i];` with just `sum += i;`) I got almost the same results as you did. So, I presume that you did run the benchmark against the correct code, but forgot to update it maybe?

**Comment by marko-lohert** [comment]
Hi,
Thank you for letting me know that there is a bug!
I’ll put fixing this bug on my to-do list for this weekend.

It’s quite possible that I have forgot to update benchmark results in code. I have worked on this benchmark in iterations -  tweaking it and preparing it for the yesterday presentation.

I plan to talk again about high performance C# code, and to use this code in a demo. So, you helped me by sending this message before my next talk. Thank you for letting me know there’s a bug - I apricated it!

**Comment by marko-lohert** [comment]
Hi,
I have fixed this issue in ForeachVsFor.cs.

Additionally,  I have dig deeper in differences between foreach and for regarding the speed.
I have added another benchmark – it’s similar as the first one but in this new benchmark ForeachVsFor_IterateThrough_Array.cs an arrary int[] is used instead of List<int>. The ratio is different – now foreach is faster
For example in case of array with 1000000  elements:
| ForEach |  1000000 | 417,287.484 ns | 1,646.2392 ns | 1,539.8932 ns |  1.00 |    0.00 |
|     For |  1000000 | 599,871.966 ns | 2,026.4008 ns | 1,895.4965 ns |  1.44 |    0.01 |


While I have planned to add this second benchmark I have decided to renamed the first benchmark: ForeachVsFor.cs -> ForeachVsFor_IterateThrough_List.cs.
Also, I have put both of these benchmarks in a Loop\ForeachVsFor folder in order to group them.

**Comment by IvanFeric** [comment]
Wow, I never would have guessed that arrays would be different than lists when it comes to looping. Great work!

**Comment by marko-lohert** [comment]
Thank you :)
